USE [master]
GO
/****** Object:  Database [DatingSite]    Script Date: 7/24/2019 10:54:45 AM ******/
CREATE DATABASE [DatingSite]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DatingSite', FILENAME = N'C:\Users\Muss Mesmari\DatingSite.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DatingSite_log', FILENAME = N'C:\Users\Muss Mesmari\DatingSite_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [DatingSite] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DatingSite].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DatingSite] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DatingSite] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DatingSite] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DatingSite] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DatingSite] SET ARITHABORT OFF 
GO
ALTER DATABASE [DatingSite] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DatingSite] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DatingSite] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DatingSite] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DatingSite] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DatingSite] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DatingSite] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DatingSite] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DatingSite] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DatingSite] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DatingSite] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DatingSite] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DatingSite] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DatingSite] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DatingSite] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DatingSite] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DatingSite] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DatingSite] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DatingSite] SET  MULTI_USER 
GO
ALTER DATABASE [DatingSite] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DatingSite] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DatingSite] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DatingSite] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DatingSite] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DatingSite] SET QUERY_STORE = OFF
GO
USE [DatingSite]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [DatingSite]
GO
/****** Object:  Table [dbo].[Answer]    Script Date: 7/24/2019 10:54:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Answer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[QuestionId] [int] NOT NULL,
	[Text] [varchar](50) NULL,
	[Score] [int] NULL,
 CONSTRAINT [PK_Answer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 7/24/2019 10:54:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Age] [int] NULL,
	[Gender] [varchar](50) NULL,
	[Sexuality] [varchar](50) NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Question]    Script Date: 7/24/2019 10:54:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Question](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Text] [varchar](50) NULL,
 CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserAnswerForQuestion]    Script Date: 7/24/2019 10:54:45 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserAnswerForQuestion](
	[UserId] [int] NOT NULL,
	[AnswerId] [int] NOT NULL,
	[Important] [bit] NULL,
 CONSTRAINT [PK_UserAnswerForQuestion] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[AnswerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Answer]  WITH CHECK ADD  CONSTRAINT [FK_Answer_Question] FOREIGN KEY([QuestionId])
REFERENCES [dbo].[Question] ([Id])
GO
ALTER TABLE [dbo].[Answer] CHECK CONSTRAINT [FK_Answer_Question]
GO
ALTER TABLE [dbo].[UserAnswerForQuestion]  WITH CHECK ADD  CONSTRAINT [FK_UserAnswerForQuestion_Answer] FOREIGN KEY([AnswerId])
REFERENCES [dbo].[Answer] ([Id])
GO
ALTER TABLE [dbo].[UserAnswerForQuestion] CHECK CONSTRAINT [FK_UserAnswerForQuestion_Answer]
GO
ALTER TABLE [dbo].[UserAnswerForQuestion]  WITH CHECK ADD  CONSTRAINT [FK_UserAnswerForQuestion_Person] FOREIGN KEY([UserId])
REFERENCES [dbo].[Person] ([Id])
GO
ALTER TABLE [dbo].[UserAnswerForQuestion] CHECK CONSTRAINT [FK_UserAnswerForQuestion_Person]
GO
USE [master]
GO
ALTER DATABASE [DatingSite] SET  READ_WRITE 
GO
